regulatory_data_mart_ai_ready:
  target: ci
  outputs:
    ci:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT', 'dummy_account') }}"
      user: "{{ env_var('SNOWFLAKE_USER', 'dummy_user') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD', 'dummy_password') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'REG_ANALYTICS_DBT_DEVELOPER') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'REGULATORY_ANALYTICS') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'REG_ANALYTICS_WH') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA', 'CI') }}"
      threads: 4
      client_session_keep_alive: false
