USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS REG_ANALYTICS_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS REGULATORY_ANALYTICS;

CREATE SCHEMA IF NOT EXISTS REGULATORY_ANALYTICS.RAW;
CREATE SCHEMA IF NOT EXISTS REGULATORY_ANALYTICS.STAGING;
CREATE SCHEMA IF NOT EXISTS REGULATORY_ANALYTICS.CORE;
CREATE SCHEMA IF NOT EXISTS REGULATORY_ANALYTICS.MARTS;
CREATE SCHEMA IF NOT EXISTS REGULATORY_ANALYTICS.GOVERNANCE;
CREATE SCHEMA IF NOT EXISTS REGULATORY_ANALYTICS.AUDIT;

USE WAREHOUSE REG_ANALYTICS_WH;
USE DATABASE REGULATORY_ANALYTICS;

SHOW SCHEMAS IN DATABASE REGULATORY_ANALYTICS;