-- 02_create_roles_and_grants.sql
-- Purpose:
-- Create Snowflake roles for building and consuming the regulatory data mart.
-- This separates transformation ownership from stakeholder read access.

USE ROLE ACCOUNTADMIN;

-- Project roles
CREATE ROLE IF NOT EXISTS REG_ANALYTICS_ADMIN;
CREATE ROLE IF NOT EXISTS REG_ANALYTICS_DBT_DEVELOPER;
CREATE ROLE IF NOT EXISTS REG_ANALYTICS_REPORTING_READER;
CREATE ROLE IF NOT EXISTS REG_ANALYTICS_GOVERNANCE_READER;

-- Role hierarchy
-- Admin inherits all project capabilities.
GRANT ROLE REG_ANALYTICS_DBT_DEVELOPER TO ROLE REG_ANALYTICS_ADMIN;
GRANT ROLE REG_ANALYTICS_REPORTING_READER TO ROLE REG_ANALYTICS_ADMIN;
GRANT ROLE REG_ANALYTICS_GOVERNANCE_READER TO ROLE REG_ANALYTICS_ADMIN;

-- Attach project admin to ACCOUNTADMIN so your trial account can manage it.
GRANT ROLE REG_ANALYTICS_ADMIN TO ROLE ACCOUNTADMIN;

-- Warehouse usage
GRANT USAGE ON WAREHOUSE REG_ANALYTICS_WH TO ROLE REG_ANALYTICS_ADMIN;
GRANT USAGE ON WAREHOUSE REG_ANALYTICS_WH TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT USAGE ON WAREHOUSE REG_ANALYTICS_WH TO ROLE REG_ANALYTICS_REPORTING_READER;
GRANT USAGE ON WAREHOUSE REG_ANALYTICS_WH TO ROLE REG_ANALYTICS_GOVERNANCE_READER;

-- Database usage
GRANT USAGE ON DATABASE REGULATORY_ANALYTICS TO ROLE REG_ANALYTICS_ADMIN;
GRANT USAGE ON DATABASE REGULATORY_ANALYTICS TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT USAGE ON DATABASE REGULATORY_ANALYTICS TO ROLE REG_ANALYTICS_REPORTING_READER;
GRANT USAGE ON DATABASE REGULATORY_ANALYTICS TO ROLE REG_ANALYTICS_GOVERNANCE_READER;

-- dbt developer privileges.
-- This role can build transformation objects.
GRANT USAGE ON SCHEMA REGULATORY_ANALYTICS.RAW TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT USAGE ON SCHEMA REGULATORY_ANALYTICS.STAGING TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT USAGE ON SCHEMA REGULATORY_ANALYTICS.CORE TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT USAGE ON SCHEMA REGULATORY_ANALYTICS.MARTS TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT USAGE ON SCHEMA REGULATORY_ANALYTICS.GOVERNANCE TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT USAGE ON SCHEMA REGULATORY_ANALYTICS.AUDIT TO ROLE REG_ANALYTICS_DBT_DEVELOPER;

GRANT SELECT ON FUTURE TABLES IN SCHEMA REGULATORY_ANALYTICS.RAW TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA REGULATORY_ANALYTICS.RAW TO ROLE REG_ANALYTICS_DBT_DEVELOPER;

GRANT CREATE TABLE ON SCHEMA REGULATORY_ANALYTICS.STAGING TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT CREATE VIEW ON SCHEMA REGULATORY_ANALYTICS.STAGING TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT CREATE TABLE ON SCHEMA REGULATORY_ANALYTICS.CORE TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT CREATE VIEW ON SCHEMA REGULATORY_ANALYTICS.CORE TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT CREATE TABLE ON SCHEMA REGULATORY_ANALYTICS.MARTS TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT CREATE VIEW ON SCHEMA REGULATORY_ANALYTICS.MARTS TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT CREATE TABLE ON SCHEMA REGULATORY_ANALYTICS.AUDIT TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT CREATE VIEW ON SCHEMA REGULATORY_ANALYTICS.AUDIT TO ROLE REG_ANALYTICS_DBT_DEVELOPER;

-- Future read access for dbt-created objects.
GRANT SELECT ON FUTURE TABLES IN SCHEMA REGULATORY_ANALYTICS.STAGING TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA REGULATORY_ANALYTICS.STAGING TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA REGULATORY_ANALYTICS.CORE TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA REGULATORY_ANALYTICS.CORE TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA REGULATORY_ANALYTICS.MARTS TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA REGULATORY_ANALYTICS.MARTS TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA REGULATORY_ANALYTICS.AUDIT TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA REGULATORY_ANALYTICS.AUDIT TO ROLE REG_ANALYTICS_DBT_DEVELOPER;

-- Reporting readers get only governed reporting outputs.
GRANT USAGE ON SCHEMA REGULATORY_ANALYTICS.MARTS TO ROLE REG_ANALYTICS_REPORTING_READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA REGULATORY_ANALYTICS.MARTS TO ROLE REG_ANALYTICS_REPORTING_READER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA REGULATORY_ANALYTICS.MARTS TO ROLE REG_ANALYTICS_REPORTING_READER;

-- Governance readers get definitions/contracts but no raw data.
GRANT USAGE ON SCHEMA REGULATORY_ANALYTICS.GOVERNANCE TO ROLE REG_ANALYTICS_GOVERNANCE_READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA REGULATORY_ANALYTICS.GOVERNANCE TO ROLE REG_ANALYTICS_GOVERNANCE_READER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA REGULATORY_ANALYTICS.GOVERNANCE TO ROLE REG_ANALYTICS_GOVERNANCE_READER;

-- Audit read access helps stakeholders verify freshness and sign-off state.
GRANT USAGE ON SCHEMA REGULATORY_ANALYTICS.AUDIT TO ROLE REG_ANALYTICS_REPORTING_READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA REGULATORY_ANALYTICS.AUDIT TO ROLE REG_ANALYTICS_REPORTING_READER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA REGULATORY_ANALYTICS.AUDIT TO ROLE REG_ANALYTICS_REPORTING_READER;

SHOW ROLES LIKE 'REG_ANALYTICS%';