-- 05_create_dev_environment.sql
-- Purpose:
-- Create isolated developer schemas that emulate a professional dbt workflow.
--
-- RAW remains the shared source layer.
-- DEV_FASAL_* schemas are your personal dbt development workspace.
-- Official STAGING / CORE / MARTS / GOVERNANCE / AUDIT schemas are reserved
-- for reviewed production-style builds.

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE REG_ANALYTICS_WH;
USE DATABASE REGULATORY_ANALYTICS;

CREATE SCHEMA IF NOT EXISTS DEV_FASAL_STAGING;
CREATE SCHEMA IF NOT EXISTS DEV_FASAL_CORE;
CREATE SCHEMA IF NOT EXISTS DEV_FASAL_MARTS;
CREATE SCHEMA IF NOT EXISTS DEV_FASAL_GOVERNANCE;
CREATE SCHEMA IF NOT EXISTS DEV_FASAL_AUDIT;

GRANT USAGE ON SCHEMA REGULATORY_ANALYTICS.DEV_FASAL_STAGING TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT USAGE ON SCHEMA REGULATORY_ANALYTICS.DEV_FASAL_CORE TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT USAGE ON SCHEMA REGULATORY_ANALYTICS.DEV_FASAL_MARTS TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT USAGE ON SCHEMA REGULATORY_ANALYTICS.DEV_FASAL_GOVERNANCE TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT USAGE ON SCHEMA REGULATORY_ANALYTICS.DEV_FASAL_AUDIT TO ROLE REG_ANALYTICS_DBT_DEVELOPER;

GRANT CREATE TABLE ON SCHEMA REGULATORY_ANALYTICS.DEV_FASAL_STAGING TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT CREATE VIEW ON SCHEMA REGULATORY_ANALYTICS.DEV_FASAL_STAGING TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT CREATE TABLE ON SCHEMA REGULATORY_ANALYTICS.DEV_FASAL_CORE TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT CREATE VIEW ON SCHEMA REGULATORY_ANALYTICS.DEV_FASAL_CORE TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT CREATE TABLE ON SCHEMA REGULATORY_ANALYTICS.DEV_FASAL_MARTS TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT CREATE VIEW ON SCHEMA REGULATORY_ANALYTICS.DEV_FASAL_MARTS TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT CREATE TABLE ON SCHEMA REGULATORY_ANALYTICS.DEV_FASAL_GOVERNANCE TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT CREATE VIEW ON SCHEMA REGULATORY_ANALYTICS.DEV_FASAL_GOVERNANCE TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT CREATE TABLE ON SCHEMA REGULATORY_ANALYTICS.DEV_FASAL_AUDIT TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT CREATE VIEW ON SCHEMA REGULATORY_ANALYTICS.DEV_FASAL_AUDIT TO ROLE REG_ANALYTICS_DBT_DEVELOPER;

GRANT SELECT ON FUTURE TABLES IN SCHEMA REGULATORY_ANALYTICS.DEV_FASAL_STAGING TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA REGULATORY_ANALYTICS.DEV_FASAL_STAGING TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA REGULATORY_ANALYTICS.DEV_FASAL_CORE TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA REGULATORY_ANALYTICS.DEV_FASAL_CORE TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA REGULATORY_ANALYTICS.DEV_FASAL_MARTS TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA REGULATORY_ANALYTICS.DEV_FASAL_MARTS TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA REGULATORY_ANALYTICS.DEV_FASAL_GOVERNANCE TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA REGULATORY_ANALYTICS.DEV_FASAL_GOVERNANCE TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA REGULATORY_ANALYTICS.DEV_FASAL_AUDIT TO ROLE REG_ANALYTICS_DBT_DEVELOPER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA REGULATORY_ANALYTICS.DEV_FASAL_AUDIT TO ROLE REG_ANALYTICS_DBT_DEVELOPER;

SHOW SCHEMAS LIKE 'DEV_FASAL_%' IN DATABASE REGULATORY_ANALYTICS;

